#!/usr/bin/env python3
"""
Generate a compact current database reference from the live PostgreSQL schema.

Run from the Django backend directory:

    python manage.py runscript generate_sqlalchemy_db_ref
or place this file as:
    dashboard/management/commands/generate_sqlalchemy_db_ref.py

This standalone version is designed to be copied into the Django management
command location so Django's manage.py bootstraps the project settings.

Recommended location:
    backend/dashboard/management/commands/generate_sqlalchemy_db_ref.py

Run:
    python manage.py generate_sqlalchemy_db_ref

Output:
    backend/DB_MODEL_REFERENCE.md
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from sqlalchemy import MetaData, create_engine
from sqlalchemy.engine import URL
from sqlalchemy.schema import CreateIndex, CreateTable


SCHEMAS = ("ref", "public")
OUTPUT_NAME = "DB_MODEL_REFERENCE.md"


def build_sqlalchemy_url() -> URL:
    db = settings.DATABASES["default"]

    engine = db.get("ENGINE", "")
    if "postgresql" not in engine:
        raise CommandError(
            f"Expected a PostgreSQL Django database, got ENGINE={engine!r}"
        )

    return URL.create(
        drivername="postgresql+psycopg",
        username=db.get("USER") or None,
        password=db.get("PASSWORD") or None,
        host=db.get("HOST") or None,
        port=int(db["PORT"]) if db.get("PORT") else None,
        database=db.get("NAME") or None,
    )


def table_sort_key(table):
    return (table.schema or "", table.name)


def qident(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def format_default(column) -> str:
    if column.server_default is not None:
        default = column.server_default

        # PostgreSQL identity columns use SQLAlchemy Identity,
        # which does not have .arg.
        if hasattr(default, "arg"):
            return str(default.arg)

        return str(default)

    if column.identity is not None:
        identity = column.identity

        parts = ["GENERATED BY DEFAULT AS IDENTITY"]

        if identity.start is not None:
            parts.append(f"START WITH {identity.start}")

        if identity.increment is not None:
            parts.append(f"INCREMENT BY {identity.increment}")

        return " ".join(parts)

    return ""

def format_pk(column) -> str:
    return "YES" if column.primary_key else ""


def format_nullable(column) -> str:
    return "YES" if column.nullable else "NO"


def format_fk(column) -> str:
    if not column.foreign_keys:
        return ""
    refs = []
    for fk in column.foreign_keys:
        target = fk.target_fullname
        refs.append(target)
    return ", ".join(sorted(refs))


def generate_document(metadata: MetaData, engine, output_path: Path) -> None:
    lines: list[str] = []

    lines.append("# Current Database Model Reference")
    lines.append("")
    lines.append("> Generated from the live PostgreSQL database using SQLAlchemy reflection.")
    lines.append("> This file is a compact agent reference; it is not a migration history.")
    lines.append("")
    lines.append("## Schemas")
    lines.append("")
    for schema in SCHEMAS:
        tables = sorted(
            [t for t in metadata.tables.values() if t.schema == schema],
            key=lambda t: t.name,
        )
        lines.append(f"### `{schema}`")
        lines.append("")
        if not tables:
            lines.append("_No reflected tables._")
            lines.append("")
            continue
        for table in tables:
            lines.append(f"- `{table.name}`")
        lines.append("")

    lines.append("## Tables")
    lines.append("")

    for table in sorted(metadata.tables.values(), key=table_sort_key):
        schema = table.schema or "public"

        lines.append(f"### `{schema}.{table.name}`")
        lines.append("")

        lines.append("| Column | Type | Nullable | PK | Default | Foreign Key |")
        lines.append("|---|---|---|---|---|---|")

        for column in table.columns:
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{column.name}`",
                        str(column.type),
                        format_nullable(column),
                        format_pk(column),
                        format_default(column).replace("|", "\\|"),
                        format_fk(column).replace("|", "\\|"),
                    ]
                )
                + " |"
            )

        lines.append("")

        constraints = [
            f"`{c.name}`" for c in table.constraints if c.name
        ]
        if constraints:
            lines.append("Constraints:")
            lines.append("")
            for constraint in sorted(constraints):
                lines.append(f"- {constraint}")
            lines.append("")

        indexes = sorted(
            table.indexes,
            key=lambda idx: idx.name or "",
        )
        if indexes:
            lines.append("Indexes:")
            lines.append("")
            lines.append("| Index | Columns | Unique |")
            lines.append("|---|---|---|")
            for index in indexes:
                cols = ", ".join(f"`{c.name}`" for c in index.columns)
                unique = "YES" if index.unique else "NO"
                lines.append(f"| `{index.name}` | {cols} | {unique} |")
            lines.append("")

        lines.append("#### SQLAlchemy-reflected CREATE TABLE")
        lines.append("")
        lines.append("```sql")
        try:
            ddl = str(CreateTable(table).compile(dialect=engine.dialect))
            lines.extend(ddl.rstrip().splitlines())
        except Exception as exc:
            lines.append(f"-- CREATE TABLE compilation failed: {exc}")
        lines.append("```")
        lines.append("")

        if indexes:
            lines.append("#### SQLAlchemy-reflected indexes")
            lines.append("")
            lines.append("```sql")
            for index in indexes:
                try:
                    stmt = str(
                        CreateIndex(index).compile(
                            dialect=engine.dialect
                        )
                    )
                    lines.append(stmt + ";")
                except Exception as exc:
                    lines.append(f"-- INDEX compilation failed: {exc}")
            lines.append("```")
            lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")


class Command(BaseCommand):
    help = "Generate a compact live PostgreSQL model/DDL reference using SQLAlchemy reflection."

    def add_arguments(self, parser):
        parser.add_argument(
            "--output",
            default=OUTPUT_NAME,
            help="Output Markdown path relative to the Django project root.",
        )

    def handle(self, *args, **options):
        url = build_sqlalchemy_url()
        self.stdout.write(f"Connecting to {url.render_as_string(hide_password=True)}")

        engine = create_engine(url, pool_pre_ping=True)

        metadata = MetaData()

        for schema in SCHEMAS:
            self.stdout.write(f"Reflecting schema: {schema}")
            metadata.reflect(bind=engine, schema=schema)

        project_root = Path.cwd()
        output_path = Path(options["output"])
        if not output_path.is_absolute():
            output_path = project_root / output_path

        generate_document(metadata, engine, output_path)

        table_count = len(metadata.tables)
        column_count = sum(len(table.columns) for table in metadata.tables.values())

        self.stdout.write(self.style.SUCCESS("Reference generated successfully."))
        self.stdout.write(f"Tables: {table_count}")
        self.stdout.write(f"Columns: {column_count}")
        self.stdout.write(f"Output: {output_path}")
